// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRowsFromTbl(arg1) {
  return window['go']['main']['App']['GetRowsFromTbl'](arg1);
}

export function RemoveTable(arg1) {
  return window['go']['main']['App']['RemoveTable'](arg1);
}
